### ISSUE TITLE
Getting address as coordinates

### ISSUE THREAD

**Issue by Isaac37** [mo-ah-dawood/open_location_picker#1]
This not an issue am a newbie to programming , after picking an address how do i get the coordinates of that address latitude and longitude..and thanks for creating such an awesome package

**Comment by mu-dawood** [comment]
its depending on your code
if you use `OpenMapPicker` then you can get the picked location in `onSaved ` or `onChanged`  paramter

```dart
    OpenMapPicker(
      decoration: const InputDecoration(hintText: "My location"),
      onSaved: (FormattedLocation? newValue) {
        print(newValue?.lat);
        print(newValue?.lon);
      },
      onChanged: (FormattedLocation? newValue) {
        print(newValue?.lat);
        print(newValue?.lon);
      },
    ),
```

- onSaved when you save form > `search for flutter forms`
- onChanged. called when user tap done button and confirm location


if you use the scond option

```dart
Navigator.of(context).push(MaterialPageRoute(builder: (BuildContext context) {
    return OpenStreetMaps(
      options: OpenMapOptions(),
       onDone: (FormattedLocation? newValue) {
        print(newValue?.lat);
        print(newValue?.lon);
      },
      bloc: CustomBloc(const OpenMapState.selected(SelectedLocation.single(null))),
    );
  }));
```

**Comment by Isaac37** [comment]
Thanks mate really appreciate

**Comment by mu-dawood** [comment]
You are welcome
