### ISSUE TITLE
Search does sometimes not really work

### ISSUE THREAD

**Issue by thunderbug1** [mo-ah-dawood/open_location_picker#10]
The search  often seems to not find places.
Tested with version 0.0.9 
Here is a video of what I mean:
https://user-images.githubusercontent.com/1395321/165893154-e8eeebbb-ea5e-438d-b97d-68f0ac3b1eb8.mp4

**Comment by thunderbug1** [comment]
Ok so I had time to look into this problem, apparently there are cases where the Search API returns Location JSON objects, that cannot be parsed. Here an example for an exception:
![image](https://user-images.githubusercontent.com/1395321/173197707-d8abf3c9-813f-426b-a165-d64c42a5aa80.png)
This case can be reproduced by searching for "vienna" in the example application.

This is quite a severe bug as it causes no search results to show, even the valid ones.
To make it less severe I created a Workaround to show at least the results that could be parsed: https://github.com/mo-ah-dawood/open_location_picker/pull/12

We should, however, still fix the parsing bug at some point.

**Comment by mu-dawood** [comment]
version 0.1.1
