### ISSUE TITLE
FormattedLocation.fromLatLng wrong argument order in geojson

### ISSUE THREAD

**Issue by franzmueller** [mo-ah-dawood/open_location_picker#14]
The arguments in FormattedLocation.fromLatLng are in the wrong order when no geojson is provided.

https://github.com/mo-ah-dawood/open_location_picker/blob/56f90484c3b2c0337c8d04db87d57e922f531f20/lib/src/location_model.dart#L158

Providing the geojson when calling the method works around this issue:
```
FormattedLocation.fromLatLng(
     lat: value.latitude,
     lon: value.longitude,
     geojson: GeoGeometry.point(
          LatLng(value.latitude, value.longitude),
          Color((Random().nextDouble() * 0xFFFFFF).toInt()).withOpacity(1.0)),
);
```

**Comment by mu-dawood** [comment]
thanks 
ver `0.2.0`
