### ISSUE TITLE
Wont actually let you select a precide location.

### ISSUE THREAD

**Issue by amigax** [mo-ah-dawood/open_location_picker#2]
Wont actually let you select a precide location.

**Comment by mu-dawood** [comment]
```dart     
    OpenMapSettings(
      reverseZoom: ReverseZoom.suburb,// try to change this
    );
```

**Comment by TheFreal** [comment]
Is there no way to disable reversezoom though? I need users to select specific coordinates, not a building or a street. Setting reverseZoom to "null" defaults it to building.

**Comment by mu-dawood** [comment]
by default we don't apply zoom 
the package sends zoom only if it was set
we use [nominatim](https://nominatim.org/release-docs/latest/api/Reverse)
which use `building` as the default zoom
