### ISSUE TITLE
Map is blank in dark mode

### ISSUE THREAD

**Issue by xmine64** [mo-ah-dawood/open_location_picker#7]
Despite map tiles are loaded correctly, they're not getting displayed in the view and it's not flutter_map's problem: https://github.com/fleaflet/flutter_map/issues/1221

**Comment by mu-dawood** [comment]
I see the problem  is the color filter in the web
you can use `getMapTileOptions` in `OpenMapSettings` for now till the next release

```dart
OpenMapSettings(
    getMapTileOptions: (_, __, provider) {
        return TileLayerOptions(
          urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
          subdomains: ['a', 'b', 'c'],
          tileBuilder: (context, tileWidget, tile) {
            return tileWidget;
          },
          tileProvider: provider,
        );
      },
   child: MaterialApp()
)
```

**Comment by xmine64** [comment]
Thanks

**Comment by mu-dawood** [comment]
now in version 0.0.7 no color filter for the web platform
