### ISSUE TITLE
Bounding box moves around map when zooming on phone

### ISSUE THREAD

**Issue by thunderbug1** [mo-ah-dawood/open_location_picker#9]
When the widget was used to select a city which has a bounding box on the map 
then when zooming, the bounding box leaves the place and flies around the map.

**Comment by mu-dawood** [comment]
can you please add screen record for your issue
and what is the version you are using

**Comment by thunderbug1** [comment]
sure, this is in the pubspec.yaml:
  open_location_picker: ^0.0.6

I was only able to reproduce this on my phone, didn't try the emulator.

Here is a video of it:
https://user-images.githubusercontent.com/1395321/165837212-8c45e616-fe42-4e8d-a796-3a2bfaff34dc.mp4

**Comment by mu-dawood** [comment]
try version 0.0.9

**Comment by thunderbug1** [comment]
yep, that fixed it. Many thanks :D
